name: Run Tests for Laravel

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      status: ${{ job.status }}
    steps:
      - uses: yuyungyang/platform@master
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
